# Generated by Django 3.2.9 on 2021-12-16 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_start_time', models.CharField(max_length=50)),
                ('choice', models.CharField(choices=[('experienced', 'Experienced'), ('fresher', 'Fresher')], max_length=20)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('experienced', 'Experienced'), ('fresher', 'Fresher')], max_length=20)),
                ('filename', models.IntegerField()),
                ('question', models.CharField(max_length=250)),
            ],
            options={
                'unique_together': {('choice', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='InterviewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
            ],
        ),
    ]
