# Generated by Django 4.0 on 2021-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdetail',
            name='correct_answer',
            field=models.TextField(default='aa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewdetail',
            name='frequency',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewdetail',
            name='nature',
            field=models.TextField(default='c'),
            preserve_default=False,
        ),
    ]
