# Generated by Django 4.0 on 2021-12-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewdetail_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdetail',
            name='analysis',
            field=models.TextField(default='fr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewdetail',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
