# Generated by Django 3.2 on 2021-11-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20211122_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
