# Generated by Django 3.1.7 on 2021-12-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview', '0003_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('experienced', 'Experienced'), ('fresher', 'Fresher')], max_length=80)),
                ('filename', models.CharField(max_length=12)),
                ('question', models.CharField(max_length=250)),
            ],
            options={
                'unique_together': {('choice', 'filename')},
            },
        ),
    ]
