# Generated by Django 4.0 on 2021-12-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewdetail_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdetail',
            name='frequency',
            field=models.FloatField(),
        ),
    ]
