# Generated by Django 4.0 on 2021-12-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_interviewdetail_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdetail',
            name='correction_frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
