# Generated by Django 3.2.9 on 2021-12-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20211202_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='filename',
            field=models.IntegerField(),
        ),
    ]
