# Generated by Django 3.2.9 on 2022-03-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_alter_interviewdetail_correction_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewdetail',
            old_name='frequency',
            new_name='stopWords_frequency',
        ),
    ]
