# Generated by Django 3.2.9 on 2022-03-30 20:19

import django.core.validators
from django.db import migrations, models
import interview.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_rename_frequency_interviewdetail_stopwords_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('initial', 'Initial'), ('intermediate', 'Intermediate'), ('concluding', 'Concluding')], default='initial', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(null=True, upload_to=interview.models.create_path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='question',
            name='filename',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('choice', 'section', 'filename')},
        ),
    ]
