# Generated by Django 3.2.9 on 2022-03-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_auto_20220331_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='filename',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
