# Generated by Django 3.1 on 2022-04-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_auto_20220402_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdetail',
            name='confidence_percent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
